export const WORDS = [
  'alabar', 'abrigo', 'adorno',
  'buscar', 'bailar', 'blando',
  'cantar', 'cerrar', 'cubrir',
  'danzar', 'debate', 'dulzor',
  'escudo', 'elevar', 'ensayo',
  'flotar', 'fiable', 'fulgor',
  'grabar', 'gancho', 'grieta',
  'herida', 'huecos', 'humano',
  'ingles', 'idioma', 'indice',
  'justos', 'jaguar', 'jardin',
  'kiosco', 'karate', 'kiloso',
  'luchar', 'labios', 'lograr',
  'mirada', 'manjar', 'maduro',
  'normal', 'noches', 'nutria',
  'oculto', 'oficio', 'objeto',
  'pintar', 'paloma', 'padres',
  'quemar', 'quejas', 'quitar',
  'ranura', 'receta', 'rostro',
  'saludo', 'semana', 'santos',
  'tomate', 'turbio', 'tarifa',
  'unirme', 'usurpa', 'utopia',
  'vender', 'velero', 'verter',
  'whisky',
  'yogurt',
  'zafiro',
]